"project_id" : "CROWDIN_PROJECT_ID"
"api_token" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": false

"files": [
  {
    "source": "/whitepaper/en/*.md",
    "translation": "/intl/%two_letters_code%/%original_file_name%"
  },
  {
    "source": "/whitepaper/en/title.yml",
    "dest": "/whitepaper/%original_file_name%",
    "translation": "/intl/%two_letters_code%/%original_file_name%"
  }
]

#files:
#  - source: /en/*.*
#    ignore:
#      - /intl/
#      - /templates
#      - /img
#      - /en/*/img
#    translation: /intl/%two_letters_code%/%original_file_name%
